package io.github.toolazytoname.xiaohei;
import java.nio.file.*; import java.util.*;
/** Nine synthetic, non-private rounds: protocol/policy/budget/result/cleanup, never a real OpenCode call. */
public final class OpenCodeAcceptanceMatrixTest {
 public static void main(String[] a)throws Exception{Path root=Files.createTempDirectory("xiaohei-oc-accept-");try{int ok=0;for(OpenCodeTaskProtocol.Kind k:OpenCodeTaskProtocol.Kind.values())for(int r=0;r<3;r++){Fixture f=fixture(root,k,r);String intent=k==OpenCodeTaskProtocol.Kind.PROJECT_SUMMARY?"总结项目":k==OpenCodeTaskProtocol.Kind.TEST_DIAGNOSIS?"诊断测试失败":"整理报告文件";if(OpenCodeToolPolicy.evaluate(k,intent).decision==OpenCodeToolPolicy.Decision.DENY)throw new AssertionError("policy");OpenCodeBoundedRunner.Result x=new OpenCodeBoundedRunner().run(f.task,f.lease,budget(k),(t,l,b,c)->{b.consumeTokens(1);b.recordStep();b.appendRedactedOutput("ok");},new OpenCodeBoundedRunner.Cancellation());if(x.code!=OpenCodeBoundedRunner.Code.SUCCESS||OpenCodeWorkspaceBoundary.release(f.lease).code!=OpenCodeWorkspaceBoundary.Code.CREATED)throw new AssertionError("round");ok++;} denial();System.out.println("PASS OpenCodeAcceptanceMatrixTest rounds=9 summary=3 diagnosis=3 organization=3 results=9 cleanup=9 denial=3 real_opencode=0");}finally{Files.walk(root).sorted(Comparator.reverseOrder()).forEach(p->{try{Files.deleteIfExists(p);}catch(Exception e){throw new AssertionError(e);}});}}
 static void denial(){for(OpenCodeTaskProtocol.Kind k:OpenCodeTaskProtocol.Kind.values())if(OpenCodeToolPolicy.evaluate(k,"git push https://x").decision!=OpenCodeToolPolicy.Decision.DENY)throw new AssertionError("deny");}
 static OpenCodeBoundedRunner.Budget budget(OpenCodeTaskProtocol.Kind k){return new OpenCodeBoundedRunner.Budget(OpenCodeBoundedRunner.Profile.LOCAL_SMALL,k==OpenCodeTaskProtocol.Kind.PROJECT_SUMMARY?OpenCodeBoundedRunner.Agent.ANALYZE:k==OpenCodeTaskProtocol.Kind.TEST_DIAGNOSIS?OpenCodeBoundedRunner.Agent.DIAGNOSE:OpenCodeBoundedRunner.Agent.ORGANIZE,500,4,2,32);}
 static Fixture fixture(Path root,OpenCodeTaskProtocol.Kind k,int r){UnconfirmedActionRequest.Result q=UnconfirmedActionRequest.fromConversationMessage(new MemoryConversationSession.Message(MemoryConversationSession.Role.USER,"帮我整理这个项目的结构"),"request-accept-public-000"+r,"2026-08-10T15:20:00Z");OpenCodeTaskProtocol.Result t=OpenCodeTaskProtocol.create(q.request,"job-accept-public-"+k.ordinal()+"000"+r,"plan-accept-public-000"+r,k);OpenCodeWorkspaceBoundary.Result l=OpenCodeWorkspaceBoundary.allocate(root,t.task);if(t.task==null||l.lease==null)throw new AssertionError("fixture");return new Fixture(t.task,l.lease);}
 static final class Fixture{final OpenCodeTaskProtocol.Task task;final OpenCodeWorkspaceBoundary.Lease lease;Fixture(OpenCodeTaskProtocol.Task t,OpenCodeWorkspaceBoundary.Lease l){task=t;lease=l;}}
}
